### Get all contacts
GET http://localhost:8080/contacts
Accept: application/json

###

### Get single contact by ID
GET http://localhost:8080/contacts/{id}
Accept: application/json

###

### Create new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Giovanni",
  "lastName": "Canavesi",
  "email": "giovanni@example.com",
  "favoriteColor": "Blue",
  "birthday": "1990-05-20"
}

###

### Update contact by ID (replace all fields)
PUT http://localhost:8080/contacts/{id}
Content-Type: application/json

{
  "firstName": "UpdatedName",
  "lastName": "UpdatedLastName",
  "email": "updated@example.com",
  "favoriteColor": "Red",
  "birthday": "1992-07-15"
}

###

### Delete contact by ID
DELETE http://localhost:8080/contacts/{id}
